services:
  - type: web
    name: laravel-api
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
        - .env
        - render.yaml
